/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nba;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author Arne
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lidnummerLabel = new javax.swing.JLabel();
        wachtwoordLabel = new javax.swing.JLabel();
        wachtwoordVeld = new javax.swing.JPasswordField();
        lidnummerVeld = new javax.swing.JTextField();
        loginButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lidnummerLabel.setText("Lidnummer");

        wachtwoordLabel.setText("Wachtwoord");

        wachtwoordVeld.setName("wachtwoordVeld"); // NOI18N

        lidnummerVeld.setActionCommand("<Not Set>");
        lidnummerVeld.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        lidnummerVeld.setName("lidnummerVeld"); // NOI18N

        loginButton.setText("Login");
        loginButton.setName("login"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(wachtwoordLabel)
                    .addComponent(lidnummerLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(loginButton)
                    .addComponent(wachtwoordVeld)
                    .addComponent(lidnummerVeld))
                .addContainerGap(140, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lidnummerLabel)
                    .addComponent(lidnummerVeld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wachtwoordLabel)
                    .addComponent(wachtwoordVeld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addComponent(loginButton)
                .addGap(32, 32, 32))
        );

        lidnummerLabel.getAccessibleContext().setAccessibleName("Login");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
            
        });
        
    }

    public JLabel getLidnummerLabel() {
        return lidnummerLabel;
    }

    public void setLidnummerLabel(JLabel lidnummerLabel) {
        this.lidnummerLabel = lidnummerLabel;
    }

    public JTextField getLidnummerVeld() {
        return lidnummerVeld;
    }

    public void setLidnummerVeld(JTextField lidnummerVeld) {
        this.lidnummerVeld = lidnummerVeld;
    }

    public JButton getLoginButton() {
        return loginButton;
    }

    public void setLoginButton(JButton loginButton) {
        this.loginButton = loginButton;
    }

    public JLabel getWachtwoordLabel() {
        return wachtwoordLabel;
    }

    public void setWachtwoordLabel(JLabel wachtwoordLabel) {
        this.wachtwoordLabel = wachtwoordLabel;
    }

    public JPasswordField getWachtwoordVeld() {
        return wachtwoordVeld;
    }

    public void setWachtwoordVeld(JPasswordField wachtwoordVeld) {
        this.wachtwoordVeld = wachtwoordVeld;
    }
    
    public void parseLidnummerNaarInteger(String lidnummerVeld) {
        int lidnummerInt = Integer.parseInt(lidnummerVeld);
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lidnummerLabel;
    private javax.swing.JTextField lidnummerVeld;
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel wachtwoordLabel;
    private javax.swing.JPasswordField wachtwoordVeld;
    // End of variables declaration//GEN-END:variables


}
